development:
  adapter: postgresql
  encoding: unicode
  database: ignite_development
  host: localhost
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: ignite_test
  host: localhost
  pool: 5
  username: postgres
  password: root